[project]
name = "json-lawgic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "json-logic>=0.6.3",
    "ruff>=0.7.4",
]

[tool.ruff]
line-length = 120